"""create pass

Revision ID: 6b43cb33eddc
Revises: 5e59d6218b92
Create Date: 2022-03-31 18:40:14.742204+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b43cb33eddc'
down_revision = '5e59d6218b92'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parts',
    sa.Column('pn', sa.String(length=64), nullable=False),
    sa.Column('ptype', sa.String(length=64), nullable=False),
    sa.Column('manufacturer_id', sa.String(length=64), nullable=True),
    sa.Column('start_gpstime', sa.BigInteger(), nullable=False),
    sa.Column('stop_gpstime', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('pn')
    )
    op.create_table('apriori_status',
    sa.Column('pn', sa.Text(), nullable=False),
    sa.Column('start_gpstime', sa.BigInteger(), nullable=False),
    sa.Column('stop_gpstime', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['pn'], ['parts.pn'], ),
    sa.PrimaryKeyConstraint('pn', 'start_gpstime')
    )
    op.create_table('part_info',
    sa.Column('pn', sa.String(length=64), nullable=False),
    sa.Column('posting_gpstime', sa.BigInteger(), nullable=False),
    sa.Column('comment', sa.String(length=2048), nullable=False),
    sa.Column('reference', sa.String(length=256), nullable=True),
    sa.ForeignKeyConstraint(['pn'], ['parts.pn'], ),
    sa.PrimaryKeyConstraint('pn', 'posting_gpstime')
    )
    op.create_table('stations',
    sa.Column('station_name', sa.String(length=64), nullable=False),
    sa.Column('station_type', sa.String(length=64), nullable=False),
    sa.Column('datum', sa.String(length=64), nullable=True),
    sa.Column('tile', sa.String(length=64), nullable=True),
    sa.Column('northing', sa.Float(precision='53'), nullable=True),
    sa.Column('easting', sa.Float(precision='53'), nullable=True),
    sa.Column('elevation', sa.Float(), nullable=True),
    sa.Column('created_gpstime', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('station_name')
    )
    op.create_table('connections',
    sa.Column('upstream_part', sa.String(length=64), nullable=False),
    sa.Column('upstream_output_port', sa.String(length=64), nullable=False),
    sa.Column('downstream_part', sa.String(length=64), nullable=False),
    sa.Column('downstream_input_port', sa.String(length=64), nullable=False),
    sa.Column('start_gpstime', sa.BigInteger(), nullable=False),
    sa.Column('stop_gpstime', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['downstream_part'], ['parts.pn'], ),
    sa.ForeignKeyConstraint(['upstream_part'], ['parts.pn'], ),
    sa.PrimaryKeyConstraint('upstream_part', 'upstream_output_port', 'downstream_part', 'downstream_input_port', 'start_gpstime')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('connections')
    op.drop_table('station')
    op.drop_table('parts')
    op.drop_table('part_info')
    op.drop_table('apriori_antenna')
    # ### end Alembic commands ###
